### ISSUE TITLE
Error 105 When Layout Exists

### ISSUE THREAD

**Issue by drewwesley** [timdietrich/fmwebframe#1]
I'm getting this error:

ExecuteSQL ( "SELECT * FROM .........", "[[[ROW]]]" )fmExecuteSQL failed with error 105 (Layout is missing.) even though the layout is there and the database connect call authenticates...

However, the FileMaker API for PHP works.

The database is hosted on FileMaker Server 11.

**Comment by timdietrich** [comment]
The ExecuteSQL function was introduced in FileMaker 12 ( http://www.filemaker.com/help/12/fmp/html/func_ref3.33.6.html ). So you'll need at least FMS 12 in order to make use of the function via FMWebFrame.

**Comment by drewwesley** [comment]
Oh, gotcha. Thanks for the quick response. I think this is a great library. Is it compatible with PHP 7.x ? Does it handle LEFT JOIN's?
